services:
  - type: web
    name: mafia-api-server
    env: node
    plan: free
    buildCommand: "npm install -g pnpm && pnpm install --no-frozen-lockfile && cd artifacts/api-server && pnpm run build"
    startCommand: "cd artifacts/api-server && node --enable-source-maps ./dist/index.mjs"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Mkvdarilana32145@db.uulexfrpvydusifwixxy.supabase.co:5432/postgres
      - key: LIVEKIT_URL
        value: wss://mafiax-a4cmo105.livekit.cloud
      - key: LIVEKIT_API_KEY
        value: APIYri54qd9xj2r
      - key: LIVEKIT_API_SECRET
        value: 3QBRxzI3NAfHkkMjAwOjbuf7bR0RplgOfhfAO201z64B
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
